version: '3'
# da usare anche con il 'kompose' (sconsigliato per il development)
services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - microservizi-net

  ######################### utente #########################
  dbpostgresql-utente:
    container_name: postgres_utente
    image: "postgres"
    ports:
      - "5433:5432"
    volumes:
      - dbpostgresql-utente-data:/var/lib/dbpostgreesql-utente
    environment:
      POSTGRES_DB: utente
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      restart: unless-stopped
    networks:
      - utente-net

  app-utente:
    image: utente
    container_name: microservizio_utente
    build: utente-microservizio
    volumes:
      - utente-data:/var/lib/utente
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql-utente
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbpostgresql-utente:5433/utente
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    networks:
      - utente-net
      - microservizi-net
    labels:
      kompose.service.type: NodePort # in produzione useremo 'ClusterIP' per evitare il contatto diretto con l'esterno
      kompose.image-pull-policy: Never


  ######################### ospedale #########################
  dbpostgresql-ospedale:
    container_name: postgres_ospedale
    image: "postgres"
    ports:
      - "5434:5432"
    volumes:
      - dbpostgresql-ospedale-data:/var/lib/dbpostgresql-ospedale
    environment:
      POSTGRES_DB: ospedale
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      restart: unless-stopped
    networks:
      - ospedale-net

  app-ospedale:
    image: ospedale
    container_name: microservizio_ospedale
    build: ospedale-microservizio
    volumes:
      - ospedale-data:/var/lib/ospedale
    ports:
      - "8081:8080"
    depends_on:
      - dbpostgresql-ospedale
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbpostgresql-ospedale:5434/ospedale
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    networks:
      - ospedale-net
      - microservizi-net
    labels:
      kompose.service.type: NodePort # in produzione useremo 'ClusterIP' per evitare il contatto diretto con l'esterno
      kompose.image-pull-policy: Never

  ######################### negozio #########################
  dbpostgresql-negozio:
    container_name: postgres_negozio
    image: "postgres"
    ports:
      - "5435:5432"
    volumes:
      - dbpostgresql-negozio-data:/var/lib/dbpostgresql-negozio
    environment:
      POSTGRES_DB: negozio
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      restart: unless-stopped
    networks:
      - negozio-net

  app-negozio:
    image: negozio
    build: negozio-microservizio
    container_name: microservizio_negozio
    volumes:
      - negozio-data:/var/lib/negozio
    ports:
      - "8082:8080"
    depends_on:
      - dbpostgresql-negozio
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbpostgresql-negozio:5435/negozio
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - negozio-net
      - microservizi-net
    labels:
      kompose.service.type: NodePort # in produzione useremo 'ClusterIP' per evitare il contatto diretto con l'esterno
      kompose.image-pull-policy: Never

  ######################### pgadmin #########################
  pgadmin:
    container_name: pgadmin4_container_master
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 50
    ports:
      - "5050:50"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "dbpostgresql-negozio:pgsql-server"
      - "dbpostgresql-utente:pgsql-server"
      - "dbpostgresql-ospedale:pgsql-server"
    depends_on:
      - dbpostgresql-negozio
      - dbpostgresql-utente
      - dbpostgresql-ospedale
    logging:
      driver: none

#  ######################### frontend - web #########################
#  frontend-web:
#    container_name: frontend_web
#    image: marcoscale98/taass:frontend-no-apigateway
#    ports:
#      - "4200:80"
#    volumes:
#      - frontend-data:/var/lib/frontend
#    depends_on:
#      - app_negozio
#      - app_utente
#      - app_ospedale
#    networks:
#      - microservizi-net
#    labels:
#      kompose.service.type: NodePort # in produzione useremo 'ClusterIP' per evitare il contatto diretto con l'esterno
#      kompose.image-pull-policy: Always

######################### volumi #########################
volumes:
  dbpostgresql-negozio-data:
  negozio-data:
  dbpostgresql-utente-data:
  utente-data:
  dbpostgresql-ospedale-data:
  ospedale-data:
  pgadmin-data:
  rabbitmq-data:
  frontend-data:

######################### networks #########################
networks:
  negozio-net:
  utente-net:
  ospedale-net:
  microservizi-net: