version: '3'
# da usare anche con il 'kompose' (sconsigliato per il development)
services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - general-net

  ######################### utente #########################
  dbpostgresqlutente:
    container_name: postgres_utente
    image: "postgres"
    ports:
      - "5433:5432"
    volumes:
      - dbpostgresql-utente-data:/var/lib/dbpostgreesqlutente
    environment:
      POSTGRES_DB: utente
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      restart: unless-stopped
    networks:
      - general-net

  apputente:
    image: marcoscale98/taass:utente
    container_name: microservizio_utente
    volumes:
      - utente-data:/var/lib/utente
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresqlutente
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbpostgresqlutente:5433/utente
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    networks:
      - general-net
    labels:
      kompose.service.type: NodePort
      kompose.service.nodeport.port: "30000"



  ######################### ospedale #########################
  dbpostgresqlospedale:
    container_name: postgres_ospedale
    image: "postgres"
    ports:
      - "5434:5432"
    volumes:
      - dbpostgresql-ospedale-data:/var/lib/dbpostgresqlospedale
    environment:
      POSTGRES_DB: ospedale
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      restart: unless-stopped
    networks:
      - general-net

  appospedale:
    image: marcoscale98/taass:ospedale
    container_name: microservizio_ospedale
    volumes:
      - ospedale-data:/var/lib/ospedale
    ports:
      - "8081:8080"
    depends_on:
      - dbpostgresqlospedale
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbpostgresqlospedale:5434/ospedale
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    networks:
      - general-net
    labels:
      kompose.service.type: NodePort
      kompose.service.nodeport.port: "30004"

  ######################### negozio #########################
  dbpostgresqlnegozio:
    container_name: postgres_negozio
    image: "postgres"
    ports:
      - "5435:5432"
    volumes:
      - dbpostgresql-negozio-data:/var/lib/dbpostgresqlnegozio
    environment:
      POSTGRES_DB: negozio
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      restart: unless-stopped
    networks:
      - general-net

  appnegozio:
    image: marcoscale98/taass:negozio
    container_name: microservizio_negozio
    volumes:
      - negozio-data:/var/lib/negozio
    ports:
      - "8082:8080"
    depends_on:
      - dbpostgresqlnegozio
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbpostgresqlnegozio:5435/negozio
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - general-net
    labels:
      kompose.service.type: NodePort
      kompose.service.nodeport.port: "30002"

  ######################### pgadmin #########################
  pgadmin:
    container_name: pgadmin4_container_master
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 50
    ports:
      - "5050:50"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "dbpostgresql-negozio:pgsql-server"
      - "dbpostgresql-utente:pgsql-server"
      - "dbpostgresql-ospedale:pgsql-server"
    depends_on:
      - dbpostgresqlnegozio
      - dbpostgresqlutente
      - dbpostgresqlospedale
    logging:
      driver: none
    networks:
      - general-net

  ######################### frontend - web #########################
  frontendweb:
    container_name: frontend_web
    image: marcoscale98/taass:frontend
    ports:
      - "4200:80"
    volumes:
      - frontend-data:/var/lib/frontend
    depends_on:
      - appnegozio
      - apputente
      - appospedale
    networks:
      - general-net
    labels:
      kompose.service.type: NodePort
      kompose.service.nodeport.port: "30003"


######################### volumi #########################
volumes:
  dbpostgresql-negozio-data:
  negozio-data:
  dbpostgresql-utente-data:
  utente-data:
  dbpostgresql-ospedale-data:
  ospedale-data:
  pgadmin-data:
  rabbitmq-data:
  frontend-data:

######################### networks #########################
networks:
  negozio-net:
  utente-net:
  ospedale-net:
  frontend-backend-net:
  general-net: