server:
  port: 8079

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id : microservizio_utente
          uri : http://localhost:8080/
          predicates:
          - Path=/utente/**
        - id : microservizio_ospedale
          uri : http://localhost:8081/
          predicates:
            - Path=/ospedale/**
        - id: microservizio_negozio
          uri: http://localhost:8082/
          predicates:
            - Path=/negozio/**

