FROM adoptopenjdk/openjdk11
#RUN addgroup --system spring && adduser --system spring --group spring
EXPOSE 8081
ARG DEPENDENCY=target
ADD ${DEPENDENCY}/*.jar ospedale.jar
ENTRYPOINT ["java","-jar","/ospedale.jar"]